### ISSUE TITLE
`go ponder` not supported

### ISSUE THREAD

**Issue by hans-ekbrand** [hans-ekbrand/lc0#11]
Since the idea with the helper is to maximise the CPU-utilization, ponder is probably never a good idea anyway, since almost no CPU resources would be left to the opponent.

**Comment by hans-ekbrand** [comment]
Still not a priority, but there are valid uses cases, e.g. bots on Lichess.

**Comment by BernardBourbaki** [comment]
Hi Hans,
Since version 178, in the gpu-nvidia-cudnn configuration, the program bugs as soon as you try to add a program (SF 14.1) in Helper.

**Comment by hans-ekbrand** [comment]
> Hi Hans, Since version 178, in the gpu-nvidia-cudnn configuration, the program bugs as soon as you try to add a program (SF 14.1) in Helper.

Hi Bernard,

1. Version 178 of what software?

2. What does it mean that the program "bugs"?

For me to able to diagnose problems run the program with AuxVerbosityLevel=10. This parameter can be set in three different ways, use on of these: (1) as a commandline option, (2) as a UCI  parameter, and lastly, (3) in the configuration file of lc0.

**Comment by BernardBourbaki** [comment]
Hi Hans,

1. **"Version 178 of what software?"** : software Lc0 with A/B Helper :
 
you have just posted v. 206   
![image](https://user-images.githubusercontent.com/76134282/161442748-9d74e0fa-210a-4837-8fc2-5c7b9623b986.png)

2. **"What does it mean that the program "bugs"?"** : the program play the 1st move and stop.

3. I show you my config with arena in gpu-nvidia-cudnn configuration :

![image](https://user-images.githubusercontent.com/76134282/161443343-c776d2c2-b90b-46b4-b2c1-da07f1fb7a3b.png)

**Comment by BernardBourbaki** [comment]
Hi Hans,

Version 233 seems to work fine !
;)

**Comment by BernardBourbaki** [comment]
Sorry,

V. 233 doesn't work...

**Comment by BernardBourbaki** [comment]
V. 234 is OK !

![image](https://user-images.githubusercontent.com/76134282/162548108-575b1742-1f66-457f-b389-fb8edde0a532.png)

**Comment by hans-ekbrand** [comment]
> V. 234 is OK !
> 
> ![image](https://user-images.githubusercontent.com/76134282/162548108-575b1742-1f66-457f-b389-fb8edde0a532.png)

Very nice, I'll close the issue then.
